language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t r4pt0s/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true r4pt0s/react-test npm test

after_success:
  - docker build -t r4pt0s/multi-client ./client
  - docker build -t r4pt0s/multi-nginx ./nginx
  - docker build -t r4pt0s/multi-server ./server
  - docker build -t r4pt0s/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push r4pt0s/multi-client
  - docker push r4pt0s/multi-nginx
  - docker push r4pt0s/multi-server
  - docker push r4pt0s/multi-worker


